//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaronteApi.Repository.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LancamentoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LancamentoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaronteApi.Repository.Resource.LancamentoResource", typeof(LancamentoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Lancamento.Lancamento SET Situacao = 0 WHERE IdLancamento = @IdLancamento.
        /// </summary>
        internal static string DeleteLancamento {
            get {
                return ResourceManager.GetString("DeleteLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF @IdCategoria = 0
        ///INSERT INTO Lancamento.Lancamento (IdUsuario, Valor, Tipo, Data, Descricao)  VALUES (@IdUsuario, @Valor, @Tipo, @Data, @Descricao)
        ///ELSE
        ///INSERT INTO Lancamento.Lancamento (IdUsuario, Valor, IdCategoria, Tipo, Data, Descricao)  VALUES (@IdUsuario, @Valor, @IdCategoria,  @Tipo, @Data, @Descricao).
        /// </summary>
        internal static string InsereLancamento {
            get {
                return ResourceManager.GetString("InsereLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select idlancamento, descricao, valor, tipo, data from lancamento.lancamento where idusuario = @idusuario and data between @dataini and @datafim and situacao = 1.
        /// </summary>
        internal static string SelectLancamento {
            get {
                return ResourceManager.GetString("SelectLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select idlancamento, idusuario, idcategoria, valor, tipo, data, descricao from lancamento.lancamento where IdLancamento = @idlancamento.
        /// </summary>
        internal static string SelectOneLancamento {
            get {
                return ResourceManager.GetString("SelectOneLancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF @IdCategoria = 0
        ///UPDATE Lancamento.Lancamento SET Valor = @Valor, Tipo = @Tipo, Data = @Data, Descricao = @Descricao WHERE IdLancamento = @IdLancamento and IdUsuario = @IdUsuario
        ///ELSE
        ///UPDATE Lancamento.Lancamento SET IdCategoria = @IdCategoria, Valor = @Valor, Tipo = @Tipo, Data = @Data, Descricao = @Descricao WHERE IdLancamento = @IdLancamento and IdUsuario = @IdUsuario.
        /// </summary>
        internal static string UpdateLancamento {
            get {
                return ResourceManager.GetString("UpdateLancamento", resourceCulture);
            }
        }
    }
}
